version: "3.9"  # optional since v1.27.0
services:
  api:
    build: ./api/.
    command: api_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=harpocrates
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  ui:
    build: ./ui/.
    command: yarn start
    ports:
      - "3000:3000"
    links:
      - api
    depends_on:
      - api
volumes:
  db:
    driver: local
